name: Lab 4 - Automated Model Deployment (CI/CD)

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python train.py

      - name: Write Job Summary
        run: |
          echo "## Lab-4 Training Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Name:** Revanth" >> $GITHUB_STEP_SUMMARY
          echo "**Roll No:** 2022BCS0210" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat metrics.json >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/
            metrics.json
  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts

      - name: Read metric
        run: |
          echo "CURR_ACC=$(jq .accuracy metrics.json)" >> $GITHUB_ENV

      - name: Compare metric
        run: |
          if (( $(echo "$CURR_ACC <= ${{ vars.BEST_F1 }}" | bc -l) )); then
            echo "<ROLL_NO>----Metric did not improve"
            exit 0
          fi

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wine_api:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wine_api:latest

      - name: Update Best Metric
        run: gh variable set BEST_F1 -b "$CURR_ACC"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
